import "../../globals.css";
import type { Metadata } from "next";
import MediumHeader from "@/components/MediumHeader";
import Container from "@/components/ui/Container";
import Sidebar from "@/components/Sidebar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="">
      <MediumHeader />
      <Container>
        <div className="flex py-[60px]">
          <Sidebar />
          <div className="pl-[40px] w-full">{children}</div>
        </div>
      </Container>
    </div>
  );
}
