import MediumHeader from "@/components/MediumHeader";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="">
      <MediumHeader />
      <div>{children}</div>
    </div>
  );
}
